### ISSUE TITLE
gitignoreについて

### ISSUE THREAD

**Issue by RyodoTanaka** [YamaCIR-KIT/cp_server#1]
.gitignoreっていうファイルを作ったら、commitの対象外にできるよ。
たとえば、このリポジトリだとbin/ディレクトリは追跡しないというのが定石なので、
gitignoreに`/bin`って書いとくだけでOKだよ。

知ってたら申し訳ない。。。

**Comment by YamaCIR-KIT** [comment]
初耳です
早速試してみます

ありがとうございました

**Comment by RyodoTanaka** [comment]
@YamaCIR-KIT 
良い感じだと思います。
後は、LINEでやりとりした通りです。
ちな、`obj`ディレクトリにある中間生成ファイルは、静的リンカを作成したりしたら、かっこ良くなると思うよ。
そのへんは、Makefileでやってもできるけど、CMakeを使うと管理しやすくなるよ。
CMakeを使った例は、[ここ](https://www.dropbox.com/s/lva20cdxrfq577r/TokyoU-Practice-master.zip?dl=0)からダウンロードしてみて

**Comment by RyodoTanaka** [comment]
@YamaCIR-KIT 
さっきのダウンロードリンクの奴は、ちょっとわかりづらかったかもしらん...
申し訳ない。
[こっち](https://github.com/Nishida-Lab/RCR2015/tree/master/Raspberry-Pi)のほうがわかりやすかったかも...

**Comment by YamaCIR-KIT** [comment]
参考にさせてもらいます

@RyodoTanaka
↑これってgithub流のアンカですか？

**Comment by RyodoTanaka** [comment]
@YamaCIR-KIT 
いえす

**Comment by YamaCIR-KIT** [comment]
なるほど
取り敢えず表題の件に関しては解決したのでこのissueは閉じときますね
